# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.network "private_network", ip: "192.168.33.12"
  config.vm.synced_folder "/Users/lionmane/Work/clients/otc_dealer_project", "/var/www/linkedtolocal/", :owner => "root", :group => "vagrant", mount_options: ["dmode=777,fmode=777"]
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "512"
  end
end
